# Meta
--- !TypesTable
class:
  type: !resolve builtins.type
  load: !resolve metaconfig.construct_from_sequence
...

# Meta
--- !TypesTable
"tag:yaml.org,2002:map":
  type: !resolve revigred.record.Record
  load: !resolve metaconfig.construct_from_mapping
...

--- !TypesTable
Constant:
  type: !resolve metaconfig.tools.Constant
  load: !resolve metaconfig.construct_from_sequence

Function:
  type: !resolve metaconfig.tools.Function
  load: !resolve metaconfig.construct_from_sequence

Try:
  type: !resolve metaconfig.tools.Try
  load: !resolve metaconfig.construct_from_sequence
...

--- !add_dependencies

NAMES: 
- James
- Christopher
- Ronald
- Mary
- Lisa
- Michelle
- John
- Daniel
- Anthony
- Patricia
- Nancy
- Laura
- Robert
- Paul
- Kevin
- Linda
- Karen
- Sarah
- Michael
- Mark
- Jason
- Barbara
- Betty
- Kimberly
- William
- Donald
- Jeff
- Elizabeth
- Helen
- Deborah
- David
- George
- Jennifer
- Sandra
- Richard
- Kenneth
- Maria
- Donna
- Charles
- Steven
- Susan
- Carol
- Joseph
- Edward
- Margaret
- Ruth
- Thomas
- Brian
- Dorothy
- Sharon

SURNAMES:
- Smith
- Anderson
- Clark
- Wright
- Mitchell
- Johnson
- Thomas
- Rodriguez
- Lopez
- Perez
- Williams
- Jackson
- Lewis
- Hill
- Roberts
- Jones
- White
- Lee
- Scott
- Turner
- Brown
- Harris
- Walker
- Green
- Phillips
- Davis
- Martin
- Hall
- Adams
- Campbell
- Miller
- Thompson
- Allen
- Baker
- Parker
- Wilson
- Garcia
- Young
- Gonzalez
- Evans
- Moore
- Martinez
- Hernandez
- Nelson
- Edwards
- Taylor
- Robinson
- King
- Carter
- Collins

...

--- !TypesTable
Chat:
  type: !resolve revigred.model.Chat
  load: !resolve metaconfig.construct_from_mapping
...

--- !add_dependencies
get_random_name: !Function
- !resolve builtins.str.format
- !Constant 
  - "{} {}"
- !Function
  - !resolve random.choice
  - !Constant 
    - !get_dependency NAMES
- !Function
  - !resolve random.choice
  - !Constant 
    - !get_dependency SURNAMES
...

--- !TypesTable
NestedSetup:
  type: !resolve logbook.NestedSetup
  load: !resolve metaconfig.construct_from_any
StreamHandler:
  type: !resolve logbook.StreamHandler
  load: !resolve metaconfig.construct_from_mapping
Logger:
  type: !resolve logbook.Logger
  load: !resolve metaconfig.construct_from_string
...

--- !add_dependencies
server:
  logging:
    logger: !Logger revigred.Server
    handler: !NestedSetup
    - !StreamHandler
      stream: !resolve sys.stdout
      format_string: '[{record.time:%Y-%m-%d %H:%M}] {record.level_name:8s}: {record.channel}: {record.message}'
  host: 127.0.0.1
  port: 9000
  model: !Chat
    names_generator: !get_dependency get_random_name
...
